version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: videoguard-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data_dev:/data/db
    ports:
      - "27017:27017"
    networks:
      - videoguard-network-dev

  # Backend API (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: videoguard-backend-dev
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://admin:admin123@mongodb:27017
      - DB_NAME=videoguard_dev
      - CORS_ORIGINS=*
    volumes:
      - ./backend:/app
      - recordings_data_dev:/app/recordings
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - videoguard-network-dev
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  # Frontend (Development with hot reload)
  frontend:
    image: node:20-alpine
    container_name: videoguard-frontend-dev
    restart: unless-stopped
    working_dir: /app
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - videoguard-network-dev
    command: sh -c "yarn install && yarn start"

volumes:
  mongodb_data_dev:
    driver: local
  recordings_data_dev:
    driver: local

networks:
  videoguard-network-dev:
    driver: bridge